# Factory-to-Customer Shipping Route Efficiency Analysis  
## Data Cleaning & Feature Engineering Phase

**Project:** Nassau Candy Distributor Logistics Analysis  
**Objective:** Prepare and validate dataset for route efficiency analysis  
**Author:** Abhi  
**Date:** 04-03-2026

## 1. Import Required Libraries

Importing essential Python libraries for data manipulation and analysis.

In [1]:
# Import core libraries for data manipulation, numerical operations, and visualization

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 2. Load Dataset

Loading raw dataset from the data directory.

In [2]:
# Load raw dataset from the data directory
# Using relative path since notebook is inside 'notebooks/' folder

df = pd.read_csv("../data/Nassau Candy Distributor.csv")

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

## 3. Initial Dataset Inspection

Performing structural validation of the dataset:
- Number of rows and columns
- Data types
- Missing values
- Statistical overview

In [4]:
# Check dataset dimensions (rows, columns)

df.shape

(10194, 18)

In [5]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost'],
      dtype='object')

In [6]:
# Inspect data types and confirm presence of null values

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

In [7]:
# Generate statistical summary for numerical columns
# Helps detect anomalies or unrealistic values

df.describe()

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost
count,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,134468.961154,13.908537,3.791838,9.166451,4.742087
std,2942.898656,20231.483007,11.341020,2.228317,6.643740,5.061647
min,1.000000,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,117212.000000,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,133550.000000,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,152051.000000,18.000000,5.000000,12.250000,5.700000
max,10194.000000,192314.000000,260.000000,14.000000,130.000000,130.000000

## 4. Date Format Standardization

Converting Order Date and Ship Date columns to datetime format for accurate lead time calculation.

In [8]:
# Convert date columns to datetime format for accurate time calculations

df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d-%m-%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d-%m-%Y')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(10)
memory usage: 1.4+ MB

## 5. Lead Time Calculation

Creating shipping lead time metric (Ship Date - Order Date).
This metric will serve as the foundation for route efficiency analysis.

In [10]:
# Calculate shipping lead time in days (core efficiency metric)

df['lead_time'] = (df['Ship Date'] - df['Order Date']).dt.days

In [11]:
# Examine distribution of lead time to detect unrealistic shipping durations

df['lead_time'].describe()

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: lead_time, dtype: float64

## 6. Lead Time Validation

Validating:
- Negative lead times
- Unrealistic values
- Data consistency

In [12]:
# Check for negative lead times (data integrity validation)

df[df['lead_time'] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Country/Region, City, State/Province, Postal Code, Division, Region, Product ID, Product Name, Sales, Units, Gross Profit, Cost, lead_time]
Index: []

In [13]:
df[['Order Date','Ship Date']].head(10)

  Order Date  Ship Date
0 2024-01-03 2026-06-30
1 2024-01-04 2026-07-01
2 2024-01-04 2026-07-01
3 2024-01-04 2026-07-01
4 2024-01-05 2026-07-05
5 2024-01-06 2026-07-03
6 2024-01-06 2026-07-03
7 2024-01-06 2026-06-30
8 2024-01-06 2026-07-03
9 2024-01-06 2026-07-03

In [14]:
# Order Date Range

print(df['Order Date'].min(), "to", df['Order Date'].max())

2024-01-02 00:00:00 to 2025-12-31 00:00:00

In [15]:
# Ship Date Range

print(df['Ship Date'].min(), "to", df['Ship Date'].max())

2026-06-30 00:00:00 to 2030-06-28 00:00:00

In [16]:
df[['Order Date','Ship Date','lead_time']].head(10)

  Order Date  Ship Date  lead_time
0 2024-01-03 2026-06-30        909
1 2024-01-04 2026-07-01        909
2 2024-01-04 2026-07-01        909
3 2024-01-04 2026-07-01        909
4 2024-01-05 2026-07-05        912
5 2024-01-06 2026-07-03        909
6 2024-01-06 2026-07-03        909
7 2024-01-06 2026-06-30        906
8 2024-01-06 2026-07-03        909
9 2024-01-06 2026-07-03        909

## 7. Financial Integrity Validation

Ensuring:
- Sales ≥ 0
- Cost ≥ 0
- Gross Profit = Sales - Cost

In [17]:
df = df.drop_duplicates()

In [18]:
df['Profit_Margin'] = df['Gross Profit'] / df['Sales']

In [19]:
df.describe()

,Row ID,Order Date,Ship Date,Customer ID,Sales,Units,Gross Profit,Cost,lead_time,Profit_Margin
count,10194.000000,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2025-03-13 03:08:26.415538176,2028-10-23 23:20:43.790465024,134468.961154,13.908537,3.791838,9.166451,4.742087,1320.841868,0.665140
min,1.000000,2024-01-02 00:00:00,2026-06-30 00:00:00,100006.000000,1.250000,1.000000,0.250000,0.600000,904.000000,0.076923
25%,2549.250000,2024-09-28 00:00:00,2027-11-09 00:00:00,117212.000000,7.200000,2.000000,4.900000,2.400000,1271.000000,0.653333
50%,5097.500000,2025-04-06 12:00:00,2028-12-18 00:00:00,133550.000000,10.800000,3.000000,7.470000,3.600000,1274.000000,0.666667
75%,7645.750000,2025-09-16 00:00:00,2029-11-08 00:00:00,152051.000000,18.000000,5.000000,12.250000,5.700000,1638.000000,0.694444
max,10194.000000,2025-12-31 00:00:00,2030-06-28 00:00:00,192314.000000,260.000000,14.000000,130.000000,130.000000,1642.000000,0.800000
std,2942.898656,NaN,NaN,20231.483007,11.341020,2.228317,6.643740,5.061647,262.444892,0.067210

In [20]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost', 'lead_time', 'Profit_Margin'],
      dtype='object')

In [21]:
df['Division'].unique()

array(['Chocolate', 'Other', 'Sugar'], dtype=object)

In [22]:
# Saved clean data in a new csv file

df.to_csv("../data/processed/clean_shipping_data.csv", index=False)